import pandas as pd
import matplotlib.pyplot as plt
sales_data = pd.read_csv("data/sales_data.csv")
sales_data["Date"] = pd.to_datetime(sales_data["Date"])
sales_data["Month"] = sales_data["Date"].dt.strftime("%B")
total_sales = sales_data["Sales"].sum()
print("Total Sales:", total_sales)
monthly_sales = sales_data.groupby("Month")["Sales"].sum()
product_sales = sales_data.groupby("Product")["Sales"].sum()
region_sales = sales_data.groupby("Region")["Sales"].sum()
print("Best Selling Product:", product_sales.idxmax())
print("Top Sales Region:", region_sales.idxmax())
print("Highest Sales Month:", monthly_sales.idxmax())
sales_data.to_csv("output/cleaned_sales_data.csv", index=False)
monthly_sales.plot(kind="bar")
plt.title("Monthly Sales")
plt.xlabel("Month")
plt.ylabel("Sales")
plt.tight_layout()
plt.savefig("images/monthly_sales.png")
plt.show()
product_sales.plot(kind="pie", autopct="%1.1f%%")
plt.title("Product Performance")
plt.ylabel("")
plt.tight_layout()
plt.savefig("images/product_performance.png")
plt.show()
region_sales.plot(kind="bar")
plt.title("Region Wise Sales")
plt.xlabel("Region")
plt.ylabel("Sales")
plt.tight_layout()
plt.savefig("images/region_sales.png")
plt.show()